export const default_url = 'http://10.10.100.27:4000';

export const bikeBrands: string[] = [
  'Bajaj',
  'Hero',
  'TVS',
  'Suzuki',
  'Yamaha',
  'Honda',
  'Royal Enfield',
  'KTM',
  'Mahindra',
  'Benelli',
  'Harley-Davidson',
  'Kawasaki',
  'Ducati',
  'Husqvarna',
  'Aprilia',
  'Moto Guzzi',
  'Piaggio',
  'CFMoto',
  'Jawa',
  'Kymco',
];

export const modelYears: string[] = [
  '2023',
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  '2016',
  '2015',
  '2014',
  '2013',
  '2012',
  '2011',
  '2010',
  '2009',
  '2008',
  '2007',
  '2006',
  '2005',
  '2004',
];

export const bikeColors: string[] = [
  'Red',
  'Blue',
  'Black',
  'White',
  'Yellow',
  'Green',
  'Orange',
  'Silver',
  'Grey',
  'Purple',
  'Matte Black',
  'Metallic Blue',
  'Pearl White',
  'Candy Red',
  'Lime Green',
  'Dark Grey',
  'Vivid Orange',
  'Midnight Black',
  'Sunset Yellow',
  'Deep Purple',
  'Turquoise',
  'Burgundy',
  'Champagne',
  'Bronze',
  'Copper',
  'Emerald Green',
  'Ruby Red',
  'Amethyst Purple',
  'Graphite Grey',
  'Arctic White',
  'Midnight Blue',
  'Sapphire Blue',
  'Lemon Yellow',
  'Crimson Red',
  'Charcoal Black',
  'Olive Green',
  'Sky Blue',
  'Platinum Silver',
  'Tangerine Orange',
  'Magenta Pink',
  'Electric Blue',
  'Forest Green',
  'Cobalt Blue',
  'Rust Orange',
  'Gold Rush',
  'Ivory White',
  'Azure Blue',
  'Lavender Purple',
  'Gunmetal Grey',
  'Sand Beige',
];
